### ISSUE TITLE
Memory Related Nidhugg Crash

### ISSUE THREAD

**Issue by kjellwinblad** [nidhugg/nidhugg#22]
Nidhugg crashes under certain situation when memory is allocated with `malloc`. A small program that reproduces the crash can be found below. The test program is not very "realistic" but I get a similar stack trace from a crash in larger and more realistic test program. 

# Stacktrace:
[stacktrace.txt](https://github.com/nidhugg/nidhugg/files/1382073/stacktrace.txt)

# Example to reproduce the crash:
[testcase.zip](https://github.com/nidhugg/nidhugg/files/1382087/testcase.zip)

# How to run the test program
```shell
# Running the test case with two threads does not cause any crash
$ make nocrash 
nidhugg --sc test.ll -- 2
WARNING: Calling unknown external function atoi as blackbox.
Trace count: 3 (also 2 sleepset blocked)
No errors were detected
# Crash
make crash 
nidhugg --sc test.ll -- 3
WARNING: Calling unknown external function atoi as blackbox.
Makefile:13: recipe for target 'crash' failed
make: *** [crash] Segmentation fault (core dumped)
```

# Versions

Nidhugg was build from version with commit id: 5db3df3289c4c2eeea763453325a2378bef0ca67

```
clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by carlleonardsson** [comment]
OK. I have confirmed the crash. I will look into it.

**Comment by carlleonardsson** [comment]
The test case you provided is not valid input to nidhugg. This is because it violates the determinism requirement by branching on uninitialized data (the first byte in the memory returned from malloc). This nondeterminism is what causes nidhugg to crash. In this particular case, you can make your program deterministic by e.g. calling calloc instead of malloc.

I am considering adding some lightweight nondeterminism detection to nidhugg so that it would give an error message and a trace instead of crashing in some cases like this.

**Comment by kjellwinblad** [comment]
@carlleonardsson thanks for your fast responses.

I think your suggestion sounds very good as the user will otherwise be clueless about the reason for the crash if the access to uninitialized memory is due to a bug in the program. I will try to investigate if the reason for the crash with my larger program is the same but having this automatically detectable by nidhugg would be a big improvement in my opinion.

**Comment by carlleonardsson** [comment]
I have pushed some basic non-determinism detection under SC/TSO/PSO. As a bonus, there is now support for calls to calloc, which may help in determinizing programs like your example.

**Comment by kjellwinblad** [comment]
@carlleonardsson thanks, I will try it out with my lager program as soon as I get an opportunity.
