### ISSUE TITLE
nidhuggc: non-backwards compatible changes?

### ISSUE THREAD

**Issue by kostis** [nidhugg/nidhugg#28]
Some scripts for running `nidhuggc` that we had in some project (https://github.com/michaliskok/rcu) have stopped working.

I suspect that the culprit are the changes merged here (5db3df3289c4c2eeea763453325a2378bef0ca67) but perhaps it's something else.

When running e.g., the following in the `rcu/valtiny` dir, the error I get is:
<pre>
% nidhuggc -I . -- --sc --disable-mutex-init-requirement fake.c
WARNING: Unable to infer the input language for input source code.
WARNING: Guessing C.
* Nidhuggc: $ /usr/bin/clang-3.8 -o /tmp/tmp5lw7nl6u/tmplm_nzlsk.ll -S -emit-llvm -g .
clang: warning: .: 'linker' input unused
clang: warning: argument unused during compilation: '-emit-llvm'
clang: warning: argument unused during compilation: '-g'
* Nidhuggc: $ /usr/local/bin/nidhugg -transform /tmp/tmp5lw7nl6u/tmpzru4rykm.ll /tmp/tmp5lw7nl6u/tmplm_nzlsk.ll
* Nidhuggc: $ /usr/local/bin/nidhugg /tmp/tmp5lw7nl6u/tmpzru4rykm.ll -I -- --sc --disable-mutex-init-requirement fake.c
nidhugg: Unknown command line argument '-I'.  Try: '/usr/local/bin/nidhugg -help'
nidhugg: Did you mean '-sc'?

Nidhuggc Error: Command (/usr/local/bin/nidhugg) returned an error exit code (1).
</pre>

Any ideas on how to fix/bypass this are appreciated.

Also, unrelated, but even though there have been some recent changes to `manual.tex` related to the new `--optimal` and `--observer` options, the PDF version of the manual that is linked by the README text has not been updated.

**Comment by kostis** [comment]
I have found that the issue can be fixed by not leaving a space between `-I` and `.`, i.e., writing `-I.`.
I can of course do that simple change in our project, but 1) it would be nice to allow for such spaces (since they are typically allowed in most C compilers), and 2) find some change that restores backwards compatibility.

Still, I find the error message one gets in cases such as the above to be a bit hard to decipher...  it would be good if something could be done about this.

**Comment by kostis** [comment]
I am not sure I follow the reasoning.  The [manual](https://github.com/nidhugg/nidhugg/blob/master/doc/manual.pdf), in Section 3.2, specifies that `nidhuggc` can be called as:
<pre>
nidhuggc CFLAGS -- {--sc,--tso,--pso,--power,--arm} AFLAGS TFLAGS FILE.c [ -- PROGRAM_ARGS]

Here CFLAGS are switches that will be given to the C compiler,
TFLAGS are Nidhugg transformation switches, and
AFLAGS are Nidhugg analysis switches.
Furthermore, PROGRAM_ARGS, if given, will be sent as arguments to the program under test.
</pre>
Now, my reading of the above is that the ` -- ` (note the spaces) are *delimiters*.  The first one, which is **mandatory**, separates the CFLAGS from the transformation and analysis switches, and the second ` -- `, which is  **optional**, denotes the start of the program arguments.

My example has only one ` -- `, so I do not see why I do not get what I want (and used to get) rather than the thing I clearly do not want (and have arguably not specified, because the manual specifies that there should be a second ` -- ` if one wants to supply program arguments).

What am I missing?

**Comment by margnus1** [comment]
`nidhuggc --help` prints a more general form, which makes both `--` optional:
 ```
Usage: /usr/bin/nidhuggc [[COMPILER/NIDHUGGC OPTIONS --] NIDHUGG/NIDHUGGC OPTIONS] FILE [-- [PROGRAM ARGUMENTS]]
```
I'm not saying that you are wrong, but rather that the current implementation treats both the `--` as optional (provided you have no compiler or program arguments). However, it disarticulates in the case of a single `--` by assuming all compiler options starts with a `-` (whereas the `nidhugg` options include the file, that cannot (in this short form) start with a `-`). This is clearly not true, as you have provided example of, and so I suggested the `nidhuggc [NIDHUGG/NIDHUGGC OPTIONS] FILE -- [PROGRAM ARGUMENTS]` short form be dropped.

**Comment by kostis** [comment]
FWIW, I agree in dropping the short form.

Independently of what the decision is, one thing that absolutely needs to be fixed is that the manual and `nidhuggc --help` should specify the same thing.
