### ISSUE TITLE
make install not optional?

### ISSUE THREAD

**Issue by kostis** [nidhugg/nidhugg#3]
The README specifies that `make install` is optional, but it seems that `nidhuggc` requires it.

I made the system and modified my `$PATH` to include `nidhugg/src`.  I can use `nidgugg` alright, but when I try to use `nidhuggc` I get:

<pre>
kostis@sandy:~/nidhugg$ nidhugg -sc test.ll
Trace count: 3 (also 0 sleepset blocked)
No errors were detected.
kostis@sandy:~/nidhugg$ nidhuggc -O2 -- --sc --unroll=10 test.c
* Nidhuggc: $ /usr/bin/clang-3.5 -o /tmp/tmpehtslx_j/tmp3d6vsscs.ll -S -emit-llvm -g -O2 test.c
* Nidhuggc: $ /usr/local/bin/nidhugg --unroll=10 -transform /tmp/tmpehtslx_j/tmpukahh74r.ll /tmp/tmpehtslx_j/tmp3d6vsscs.ll

Nidhuggc Error: [Errno 2] No such file or directory: '/usr/local/bin/nidhugg'
</pre>

I think that either `nidhuggc` needs to be fixed to simply call `nidhugg` in the PATH, or the `README` needs to be modified to mention that the install is not optional.

**Comment by carlleonardsson** [comment]
Installation is no longer marked optional in the README.
