### ISSUE TITLE
Make fail during installation

### ISSUE THREAD

**Issue by singhsanjana** [nidhugg/nidhugg#69]
I am getting the following error on 'make' after './configure':
`.././deps/immer/immer/detail/rbts/position.hpp:1509:40: error: use of ‘template<class NodeT, class Visitor, class ... Args> decltype(auto) immer::detail::rbts::visit_maybe_relaxed_sub(NodeT*, immer::detail::rbts::shift_t, immer::detail::rbts::size_t, Visitor, Args&& ...)’ before deduction of ‘auto’
                 visit_maybe_relaxed_sub(p[i], ss, relaxed_->d.sizes[i] - s,`

I am installing on an ubuntu 18.04 machine with gcc-5 and clang-6. What could be the reason?

**Comment by margnus1** [comment]
We have not thoroughly tested with gcc-5, since it's so old. Could you try with clang (f.ex. `./configure CXX=clang++ CC=clang`) or with a newer gcc?

**Comment by singhsanjana** [comment]
Thanks, this worked.

I was earlier trying to install with gcc-7, however, I was getting the error 
`error: C++ compiler cannot create executables`
then I attempted with gcc-5.

**Comment by kostis** [comment]
Hi @singhsanjana : great that you managed to get a working nidhugg!

As far as we know, installing with newer gcc's (gcc-7) should work, so the above most likely shows that something not OK in your system.  Still, do let us know whether you notice anything else that is not working or performing as you would be expecting it to.

**Comment by margnus1** [comment]
Indeed, `error: C++ compiler cannot create executables` does not mean that the compiler is too old. It means that `configure` tried to compile a hello-world and the compiler errored. Usually it's a problem with your environment. Reading the `config.log` output file tells you what program it compiled with what flags, and what the error that the compiler gave was, and looking at it is usually enough to figure out what was wrong. It could be, for example, having a flag in the `CXXFLAGS` or `LDFLAGS` environment variables that the compiler does not understand.

As for the issue using gcc-5, I reproduced the problem and played around a bit with it. I believe there are some nontrivial incompatibilities with the immer library, so I will bump our minimum requirement to gcc-6
