### ISSUE TITLE
lock/unlock in constructor/destructor seems not working

### ISSUE THREAD

**Issue by albertnetymk** [nidhugg/nidhugg#84]
Somehow I can't use constructor/destructor to lock/unlock around `pthread_join`. The snippet doesn't have any assertion failure, but if I uncomment line `// mutex m(&lock);`, and comment out the direct call to lock/unlock in that block, nidhugg reports assertion failure.

I am running it using `nidhuggc -O -std=c++17 --   --sc   --print-progress-estimate   --extfun-no-race=printf   --extfun-no-race=putchar   --no-check-mutex-init test.cpp`.

```c
#include <pthread.h>
#include <stdio.h>

#include <cassert>

class mutex {
    pthread_mutex_t *_lock;
    public:
        mutex(pthread_mutex_t *lock) : _lock(lock) {
            pthread_mutex_lock(_lock);
        }
        ~mutex() {
            pthread_mutex_unlock(_lock);
        }
};

int count = 0;

void t0() {
  count++;
}

static pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;

int main()
{
  pthread_t threads[1];
  {
    mutex m(&lock);
    auto ret = pthread_create(&threads[0],
        nullptr,
        [](void*) -> void* { t0(); return nullptr; },
        nullptr);
    assert(ret == 0);
  }
  {
    // mutex m(&lock);
    pthread_mutex_lock(&lock);
    for (size_t i = 0; i < 1; ++i) {
      auto ret = pthread_join(threads[i], nullptr);
      assert(ret == 0);
    }
    pthread_mutex_unlock(&lock);
  }

  assert(count == 1);
  return 0;
}
```

**Comment by margnus1** [comment]
I have now debugged this issue. It's caused by having `pthread_join` inside a try/catch block. At that point, clang++ emits an llvm `invoke` instruction, instead of a `call`. Unfortunately, nidhugg's frontend was not expecting `pthread_join` (also not `pthread_mutex_lock`) to be in `invoke` instructions, thus mishandling the join.

**Comment by albertnetymk** [comment]
Thank you for fixing this.
